import Button from "@/design-systems/Atoms/Button";
import { ArrowIcon } from "@/design-systems/Atoms/Icons";
import Typography from "@/design-systems/Atoms/Typography";
import React, { useState } from "react";

const VeLQTYFeesCard: React.FC = () => {
  const [isOpen, setIsOpen] = useState<boolean>(false);

  return (
    <div className="">
      <div className="rounded-sm bg-[#1A202C] shadow-lg mb-3 border border-separator">
        <div className="flex items-center justify-between p-6">
          <Typography className="text-body font-semibold">
            veLQTY Fees
          </Typography>
          <div className="flex items-center space-x-2">
            <Button className="bg-primary w-[120px] rounded !text-black px-4 py-1 disabled:bg-white disabled:text-lightBlack disabled:opacity-30 disabled:cursor-not-allowed">
              Claim All
            </Button>
            <button
              className="focus:outline-none"
              onClick={() => setIsOpen(!isOpen)}
              aria-label="expand card content"
            >
              <ArrowIcon
                className={`transform w-8 h-8 !opactiy-50 transition-transform stroke-primary fill-primary ${
                  !isOpen ? "rotate-180" : ""
                }`}
              />
            </button>
          </div>
        </div>

        {isOpen && (
          <div className="px-6">
            <table className="w-full ">
              <thead>
                <tr className="border-b">
                  <th className="py-2 font-semibold border-separator border-b"></th>
                  <th className="py-2 font-normal text-sm border-separator border-b">
                    APR:
                  </th>
                  <th className="py-2 font-normal text-sm border-separator border-b">
                    Earned:
                  </th>
                </tr>
              </thead>

              <tbody className="border-t"></tbody>
            </table>
          </div>
        )}
        <div className="bg-primary text-black mt-4 flex md:flex-row flex-col p-4 md:gap-16 gap-4 md:justify-between items-center rounded-b-md text-center">
          <div className="flex flex-col">
            <div className="flex items-start">
              <Typography className="mb-2">
                Lock LQTY now to earn a share of the fees generated by the
                protocol.
              </Typography>
            </div>

            <Typography>
              <span className="font-bold">$78,542</span> in LUSD will be
              distributed to LQTY lockers on{" "}
              <span className="font-bold">Thu 4, 2024</span>.
            </Typography>
          </div>
          <div className="flex items-center gap-5">
            <Button className="py-[6px] hover:opacity-50 rounded px-4 w-[150pxs] border border-black !text-inherit">
              Lock All
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default VeLQTYFeesCard;
